import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import Header from '@/Components/Header/Header'
import Banner from '@/Components/Banner/Banner'
import HealthySide from '@/Components/Midpart/HealthySide'
import SectionThree from '@/Components/SectionThree/SectionThree'
import Bestfull from '@/Components/Bestfull/Bestfull'
import RespponsiveBestfull from '@/Components/Bestfull/RespponsiveBestfull'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='lg:w-[1440px] lg:h-[2500px] mx-auto w-[100%] h-[2700px]'>
      <Header/>
       <Banner/>
       <HealthySide/>
       <SectionThree/>
       <Bestfull/>
       <RespponsiveBestfull/>
      </main>
    </>
  )
}
